"""Initial schema: characters, game_sessions, discoveries, narrative_history

Revision ID: d6e547eb37b6
Revises:
Create Date: 2025-12-28 11:31:28.528488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6e547eb37b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('character_class', sa.String(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('current_location', sa.String(), nullable=False),
    sa.Column('inventory', sa.JSON(), nullable=True),
    sa.Column('turn_count', sa.Integer(), nullable=True),
    sa.Column('session_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_played', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('state_snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_character_active', 'game_sessions', ['character_id', 'is_active'], unique=False)
    op.create_table('discoveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_session_id', sa.String(), nullable=False),
    sa.Column('discovery_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_entity', 'discoveries', ['game_session_id', 'entity_id'], unique=False)
    op.create_index('idx_session_type', 'discoveries', ['game_session_id', 'discovery_type'], unique=False)
    op.create_table('narrative_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_session_id', sa.String(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('agent_used', sa.String(), nullable=True),
    sa.Column('response_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_turn', 'narrative_history', ['game_session_id', 'turn_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_session_turn', table_name='narrative_history')
    op.drop_table('narrative_history')
    op.drop_index('idx_session_type', table_name='discoveries')
    op.drop_index('idx_session_entity', table_name='discoveries')
    op.drop_table('discoveries')
    op.drop_index('idx_character_active', table_name='game_sessions')
    op.drop_table('game_sessions')
    op.drop_table('characters')
    # ### end Alembic commands ###
